global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:5000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
